import { Vehicle, Trip, Alert } from './types';

export const mockVehicles: Vehicle[] = [
  {
    id: '1',
    plateNumber: 'PGA-2024-001',
    name: 'Delivery Van 1',
    driver: 'Juan Santos',
    status: 'active',
    location: { lat: 14.5995, lng: 120.9842 },
    speed: 45,
    odometer: 125400,
    fuelLevel: 78,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: '2',
    plateNumber: 'PGB-2024-002',
    name: 'Delivery Van 2',
    driver: 'Maria Garcia',
    status: 'active',
    location: { lat: 14.6091, lng: 121.0223 },
    speed: 32,
    odometer: 98600,
    fuelLevel: 65,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: '3',
    plateNumber: 'PGC-2024-003',
    name: 'Cargo Truck 1',
    driver: 'Carlos Cruz',
    status: 'idle',
    location: { lat: 14.5550, lng: 120.9930 },
    speed: 0,
    odometer: 256800,
    fuelLevel: 42,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: '4',
    plateNumber: 'PGD-2024-004',
    name: 'Box Truck',
    driver: 'Ana Lopez',
    status: 'active',
    location: { lat: 14.6352, lng: 120.9811 },
    speed: 28,
    odometer: 54300,
    fuelLevel: 88,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: '5',
    plateNumber: 'PGE-2024-005',
    name: 'Delivery Van 3',
    driver: 'Miguel Torres',
    status: 'maintenance',
    location: { lat: 14.5500, lng: 121.0000 },
    speed: 0,
    odometer: 178900,
    fuelLevel: 0,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: '6',
    plateNumber: 'PGF-2024-006',
    name: 'Cargo Truck 2',
    driver: 'Rosa Martinez',
    status: 'active',
    location: { lat: 14.5800, lng: 120.9700 },
    speed: 52,
    odometer: 312400,
    fuelLevel: 71,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: '7',
    plateNumber: 'PGG-2024-007',
    name: 'Refrigerated Van',
    driver: 'Luis Reyes',
    status: 'offline',
    location: { lat: 14.6200, lng: 121.0150 },
    speed: 0,
    odometer: 89700,
    fuelLevel: 35,
    lastUpdated: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: '8',
    plateNumber: 'PGH-2024-008',
    name: 'Delivery Van 4',
    driver: 'Sofia Navarro',
    status: 'active',
    location: { lat: 14.5670, lng: 120.9580 },
    speed: 38,
    odometer: 145200,
    fuelLevel: 82,
    lastUpdated: new Date().toISOString(),
  },
];

export const mockTrips: Trip[] = [
  {
    id: '1',
    vehicleId: '1',
    vehicleName: 'Delivery Van 1',
    driver: 'Juan Santos',
    startLocation: 'Manila Hub',
    endLocation: 'Makati Branch',
    startTime: new Date(Date.now() - 7200000).toISOString(),
    endTime: new Date(Date.now() - 3600000).toISOString(),
    distance: 28.5,
    status: 'completed',
    fuelUsed: 4.2,
  },
  {
    id: '2',
    vehicleId: '1',
    vehicleName: 'Delivery Van 1',
    driver: 'Juan Santos',
    startLocation: 'Makati Branch',
    endLocation: 'BGC Hub',
    startTime: new Date(Date.now() - 3600000).toISOString(),
    endTime: new Date().toISOString(),
    distance: 15.3,
    status: 'in-progress',
    fuelUsed: 2.1,
  },
  {
    id: '3',
    vehicleId: '2',
    vehicleName: 'Delivery Van 2',
    driver: 'Maria Garcia',
    startLocation: 'Manila Hub',
    endLocation: 'Pasay Center',
    startTime: new Date(Date.now() - 5400000).toISOString(),
    endTime: new Date().toISOString(),
    distance: 22.8,
    status: 'completed',
    fuelUsed: 3.5,
  },
  {
    id: '4',
    vehicleId: '2',
    vehicleName: 'Delivery Van 2',
    driver: 'Maria Garcia',
    startLocation: 'Pasay Center',
    endLocation: 'Las Piñas Terminal',
    startTime: new Date(Date.now() - 1800000).toISOString(),
    endTime: new Date(Date.now() + 3600000).toISOString(),
    distance: 35.0,
    status: 'scheduled',
    fuelUsed: 0,
  },
  {
    id: '5',
    vehicleId: '6',
    vehicleName: 'Cargo Truck 2',
    driver: 'Rosa Martinez',
    startLocation: 'Manila Hub',
    endLocation: 'Quezon City Depot',
    startTime: new Date(Date.now() - 10800000).toISOString(),
    endTime: new Date(Date.now() - 7200000).toISOString(),
    distance: 45.2,
    status: 'completed',
    fuelUsed: 8.5,
  },
];

export const mockAlerts: Alert[] = [
  {
    id: '1',
    vehicleId: '3',
    vehicleName: 'Cargo Truck 1',
    type: 'Scheduled Maintenance',
    severity: 'warning',
    message: 'Vehicle due for maintenance in 3 days',
    timestamp: new Date(Date.now() - 1800000).toISOString(),
    resolved: false,
  },
  {
    id: '2',
    vehicleId: '7',
    vehicleName: 'Refrigerated Van',
    type: 'Vehicle Offline',
    severity: 'critical',
    message: 'Vehicle has been offline for 1+ hour',
    timestamp: new Date(Date.now() - 3600000).toISOString(),
    resolved: false,
  },
  {
    id: '3',
    vehicleId: '5',
    vehicleName: 'Delivery Van 3',
    type: 'In Maintenance',
    severity: 'info',
    message: 'Vehicle is currently in scheduled maintenance',
    timestamp: new Date(Date.now() - 7200000).toISOString(),
    resolved: false,
  },
  {
    id: '4',
    vehicleId: '6',
    vehicleName: 'Cargo Truck 2',
    type: 'High Speed',
    severity: 'warning',
    message: 'Vehicle exceeded speed limit (80 km/h)',
    timestamp: new Date(Date.now() - 10800000).toISOString(),
    resolved: true,
  },
  {
    id: '5',
    vehicleId: '2',
    vehicleName: 'Delivery Van 2',
    type: 'Low Fuel',
    severity: 'warning',
    message: 'Fuel level below 50%',
    timestamp: new Date(Date.now() - 14400000).toISOString(),
    resolved: false,
  },
];
